# Generated by Django 4.1.5 on 2023-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0002_client_contract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False, verbose_name='prospect'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False, verbose_name='unsigned'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False, verbose_name='uncompleted'),
        ),
    ]
