# Generated by Django 4.1.5 on 2023-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0003_alter_client_status_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False, verbose_name='signed'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False, verbose_name='signed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
