# Generated by Django 4.1.5 on 2023-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0004_alter_client_status_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
