# Generated by Django 4.1.5 on 2023-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0005_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='reference',
            field=models.CharField(default='007', max_length=25, unique=True),
        ),
    ]
