# Generated by Django 4.1.5 on 2023-01-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0006_contract_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reference',
            field=models.CharField(default='00000', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(default='00000', max_length=25, unique=True),
        ),
    ]
