# Generated by Django 4.1.5 on 2023-01-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0007_event_reference_alter_contract_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='reference',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
