# Generated by Django 4.1.5 on 2023-01-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
